feature/repo-list-pagination
PEBMED/android-base-architecture pull request #11
Opened 2021-02-26 16:58 UTC by ruanvasconcelos

Changes | Feature:

Enable repository list pagination.

2021-03-01 18:11 UTC, renanBarbieri commented on app/src/main/java/com/pebmed/basearch/presentation/ui/base/EndlessRecyclerView.kt
> +                        if (it is GridLayoutManager) it.findLastCompletelyVisibleItemPosition()
if(...) {
...
} else {
...
}

2021-03-01 18:13 UTC, renanBarbieri commented on app/src/main/java/com/pebmed/basearch/presentation/ui/main/MainActivity.kt
> -    //region ViewStates
//region VIEW STATES

2021-03-01 18:15 UTC, renanBarbieri commented on data/src/main/java/br/com/pebmed/data/repo/RepoRepositoryImpl.kt
> +        val nextPage = if(hasNextPage)  page+1 else 0
if(...) {
...
} else {
...
}

2021-03-01 23:54 UTC, renanBarbieri approved these changes

2021-03-02 00:03 UTC, renanBarbieri requested changes
Adicionar/modificar testes unitários na camada de domínio (GetReposUseCase), repositório (RepoRepositoryImpl) e ViewModel (MainViewModel)

2021-03-04 16:07 UTC, ruanvasconcelos commented
> Adicionar/modificar testes unitários na camada de domínio (GetReposUseCase), repositório (RepoRepositoryImpl) e ViewModel (MainViewModel)

Resolvido.

2021-03-04 17:04 UTC, renanBarbieri approved these changes

2021-03-04 17:04 UTC, merged